[ALPS07673475] bt: fix build errors against kernel-5.18
Fix the build breaks introduced in linux v5.18.

vendor/mediatek/kernel_modules/connectivity/bt/mt66xx/btif/btmtk_btif_main.c:268:3: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
vendor/mediatek/kernel_modules/connectivity/bt/mt66xx/btif/btmtk_char_dev.c:140:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

MTK-Commit-Id: d15a8ca4e213e16df48163914b2a80184e8906ae

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I4e4cd7c7952424e920ab63ac3e9aa8c5ead4708b