[ALPS08631203] fix kernel-6.7 build errors
Fix build error according to d844fe65f095 ("sched/headers: Move struct sched_param out of uapi, to work around glibc/musl breakage")

vendor/mediatek/kernel_modules/connectivity/bt/mt66xx/6878/../include/btif/btmtk_btif.h:208:8: error: redefinition of sched_param

MTK-Commit-Id: 033859460ff11a2d544eef7b39e99c5486245d3f

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: I588b26422f16a60800c892f8635408fb71371356