[ALPS08631203] bt: fix build error due to mainline migration
[Description]
Fix build error according to Commit "4cf6336 Merge tag v6.10-rc1 into android-mainline"
1. fix error due to "use $(src) instead of $(srctree)/$(src) for source directory"
2. include linux/vmalloc, error: call to undeclared function vfree, vmalloc, vzalloc
3. fix error: no member named dev_type in struct hci_dev

[Test]
Build and Boot up

MTK-Commit-Id: ae982a8dcf93831921de761263bd46be9888028e

Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: Ia0181dac0274497d02b168132601c89aaa8f45bc